import type { LucideIcon } from "lucide-react";
import {
	ArrowDown,
	ArrowLeft,
	ArrowLeftRight,
	ArrowUp,
	ArrowUpDown,
	Bell,
	Bitcoin,
	BookUser,
	Check,
	ChevronDown,
	ChevronRight,
	Compass,
	Copy,
	Diamond,
	Download,
	Eye,
	FileText,
	Filter,
	Flame,
	Gift,
	Globe,
	Grid2x2Plus,
	Grip,
	Headphones,
	HelpCircle,
	History,
	Info,
	LayoutDashboard,
	Link,
	Lock,
	Moon,
	PiggyBank,
	PlusCircle,
	RefreshCw,
	Repeat,
	Save,
	Scan,
	Search,
	Settings,
	Shield,
	ShieldCheck,
	SlidersHorizontal,
	Sun,
	SunMoon,
	TrendingUp,
	User,
	Wallet,
	Zap,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
	arrow_upward: ArrowUp,
	arrow_downward: ArrowDown,
	history: History,
	dashboard_customize: Grid2x2Plus,
	account_balance_wallet: Wallet,
	analytics: TrendingUp,
	swap_horizontal_circle: Repeat,
	explore: Compass,
	person: User,
	brightness_auto: SunMoon,
	light_mode: Sun,
	dark_mode: Moon,
	arrow_back: ArrowLeft,
	grid_view: Grip,
	notifications: Bell,
	diamond: Diamond,
	arrow_drop_down: ChevronDown,
	visibility: Eye,
	chevron_right: ChevronRight,
	verified_user: ShieldCheck,
	tune: SlidersHorizontal,
	check: Check,
	content_copy: Copy,
	info: Info,
	info_outline: Info,
	filter_list: Filter,
	search: Search,
	wallet: Wallet,
	security: Shield,
	shield: Shield,
	globe: Globe,
	language: Globe,
	currency_bitcoin: Bitcoin,
	help_outline: HelpCircle,
	swap_horiz: ArrowLeftRight,
	savings: PiggyBank,
	landscape: LayoutDashboard,
	bolt: Zap,
	public: Globe,
	currency_exchange: ArrowLeftRight,
	local_fire_department: Flame,
	add_circle: PlusCircle,
	swap_vert: ArrowUpDown,
	settings_lock: Lock,
	settings_backup: Download,
	settings_audit: ShieldCheck,
	settings_scan: Scan,
	settings_wallet: Wallet,
	settings_network: Globe,
	settings_address: BookUser,
	settings_preferences: Settings,
	settings_link: Link,
	settings_sync: RefreshCw,
	settings_referral: Gift,
	settings_terms: FileText,
	settings_privacy: Shield,
	settings_help: Headphones,
	settings_about: Info,
};

export default function Icon({
	name,
	size,
	className,
}: {
	name: string;
	size?: number;
	className?: string;
}) {
	const LucideIcon = MAP[name];
	if (!LucideIcon) return null;
	return <LucideIcon size={size ?? 22} className={className} />;
}

export function iconFor(name: string): LucideIcon | undefined {
	return MAP[name];
}
