export default function QrCodeIcon() {
	return (
		<svg width="140" height="140" viewBox="0 0 140 140" aria-hidden="true">
			<rect
				x="0"
				y="0"
				width="50"
				height="50"
				rx="4"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="10"
				y="10"
				width="30"
				height="30"
				rx="2"
				fill="var(--gl-background)"
			/>
			<rect
				x="90"
				y="0"
				width="50"
				height="50"
				rx="4"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="100"
				y="10"
				width="30"
				height="30"
				rx="2"
				fill="var(--gl-background)"
			/>
			<rect
				x="0"
				y="90"
				width="50"
				height="50"
				rx="4"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="10"
				y="100"
				width="30"
				height="30"
				rx="2"
				fill="var(--gl-background)"
			/>
			<rect
				x="60"
				y="60"
				width="20"
				height="20"
				rx="2"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="90"
				y="60"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="60"
				y="90"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="110"
				y="110"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="90"
				y="110"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="80"
				y="80"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="110"
				y="80"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="80"
				y="110"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="60"
				y="110"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
			<rect
				x="60"
				y="80"
				width="10"
				height="10"
				fill="var(--gl-on-background)"
			/>
		</svg>
	);
}
